version: '3'

services:
  web1:
    image: php:7.2-apache
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/log:/var/log/php
      - ./www/html:/var/www/html
    environment:
      VIRTUAL_HOST: 'web1.local'

networks:
  default:
    external: true
    name: proxy-net
