version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./html/:/var/www/html
    privileged: true
    ports:
      - 8888:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    #platform: linux/x86_64
    volumes:
      - ./mysql:/var/lib/mysql
      - .config/mysql/my.conf:/etc/mysql/conf.d/my.conf
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=n8r
      - MYSQL_PASSWORD=password
    ports:
      - 4306:3306
