version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8888:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
      - db
    restart: always

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
      - ./php/log:/var/log/php
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8889:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: always

  db:
    image: mysql:5.7
    ports: 
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.conf:/etc/mysql/conf.d/my.conf
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
